# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField(default='')),
                ('field2', models.TextField(default='')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField(default='')),
                ('field2', models.TextField(default='')),
                ('img1', models.TextField(default='')),
                ('img2', models.TextField(default='')),
                ('order', models.IntegerField()),
            ],
            bases=(sr.models.SuperFact, models.Model),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_strength', models.FloatField(default=0)),
                ('last_answered', models.DateTimeField(auto_now_add=True)),
                ('to_be_answered', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CardPic',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sr.Card')),
                ('type', models.IntegerField(default=0)),
            ],
            bases=('sr.card',),
        ),
        migrations.AddField(
            model_name='memory',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Card'),
        ),
        migrations.AddField(
            model_name='memory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factpic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Subject'),
        ),
        migrations.AddField(
            model_name='fact',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Subject'),
        ),
        migrations.AddField(
            model_name='card',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Fact'),
        ),
    ]
