# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField(default='')),
                ('field2', models.TextField(default='')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_strength', models.FloatField(default=0)),
                ('last_answered', models.DateTimeField(auto_now_add=True)),
                ('to_be_answered', models.DateTimeField(blank=True, default=None, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='fact',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Subject'),
        ),
        migrations.AddField(
            model_name='card',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Fact'),
        ),
    ]
