# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='side',
            field=models.IntegerField(default=0),
        ),
    ]
