# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='fact',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='subject',
        ),
    ]
