# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 01:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_strength', models.FloatField(default=0)),
                ('last_answered', models.DateTimeField(auto_now_add=True)),
                ('to_be_answered', models.DateTimeField(blank=True, default=None, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Card')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Fact')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
